export type SupportedPlatform = "ios" | "android";

export type LogLevel = "silent" | "info" | "debug";

export interface ServerUrlContext {
  host: string;
  port: number;
  protocol: "http" | "https";
}

export interface NetworkUrlOptions {
  /**
   * Hostname or IP address to write when Vite listens on every interface.
   * Defaults to CAP_SERVER_HOST or the first non-internal local IPv4 address.
   */
  host?: string;
}

export interface ViteCapacitorPluginOptions {
  /**
   * Override the working directory used to resolve config files.
   * Defaults to the Vite project's resolved root.
   */
  root?: string;
  /**
   * Platforms whose Capacitor config copies should be updated.
   * Defaults to both iOS and Android.
   */
  platforms?: SupportedPlatform[];
  /**
   * Path to the iOS copy generated by `npx cap sync ios`.
   * Defaults to `ios/App/App/capacitor.config.json`.
   */
  iosConfigPath?: string;
  /**
   * Path to the Android copy generated by `npx cap sync android`.
   * Defaults to `android/app/src/main/assets/capacitor.config.json`.
   */
  androidConfigPath?: string;
  /**
   * Any extra files that should receive the same server settings.
   */
  additionalConfigPaths?: string[];
  /**
   * Whether to force `server.cleartext` to true. Defaults to true.
   */
  cleartext?: boolean;
  /**
   * Verbosity level for plugin logs.
   */
  logLevel?: LogLevel;
  /**
   * Override the URL detection with a static string or a factory.
   */
  urlOverride?: string | ((context: ServerUrlContext) => string);
  /**
   * Use a LAN-reachable host when Vite is exposed with --host 0.0.0.0, --host ::,
   * or server.host === true. Defaults to false to preserve the localhost behavior.
   */
  networkUrl?: boolean | NetworkUrlOptions;
}
